/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.riflemansd.courierdb.gui.test;

import java.awt.BorderLayout;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import org.riflemansd.courierdb.CourierDBM;
import org.riflemansd.courierdb.entrys.dbs.DistributorS;
import org.riflemansd.courierdb.entrys.dbs.PackageInS;
import org.riflemansd.courierdb.entrys.dbs.PackageOutS;
import org.riflemansd.courierdb.entrys.dbs.VoucherS;
import org.riflemansd.courierdb.utils.MyUtils;

/**
 *
 * @author RiflemanSD
 */
public class Dromologisi1 extends javax.swing.JPanel {
    DianomeasPanel dianomeasPanel1;
    /**
     * Creates new form Dromologisi
     */
    public Dromologisi1() {
        initComponents();
        
        dianomeasPanel1 = new DianomeasPanel();
        this.jPanel1.add(dianomeasPanel1, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        kataxwrisiButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        voucherID = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        kataxwrisiButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kataxwrisiButton.setText("Καταχώρηση");
        kataxwrisiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kataxwrisiButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Voucher:");

        voucherID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cancelButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelButton.setText("Ακύρωση");

        jPanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(kataxwrisiButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(voucherID, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(voucherID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kataxwrisiButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void kataxwrisiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kataxwrisiButtonActionPerformed
        DistributorS dist = new DistributorS(this.dianomeasPanel1.getCurrID(), this.dianomeasPanel1.getCurrName());
        
        String voucherId = this.voucherID.getText();
        if (voucherId.isEmpty())  {
            JOptionPane.showMessageDialog(this, "Το VoucherID δεν μπορεί να είναι κενό", "Αποτυχία", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else if (MyUtils.stringToDouble(voucherId) == -1) {
            JOptionPane.showMessageDialog(this, "Το VoucherID δεν μπορεί να περιέχει χαρακτήρες", "Αποτυχία", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Date date = new Date();
        
        if (voucherId.length() != 12)  {
            int a = JOptionPane.showConfirmDialog(this, "Το VoucherID που δώσατε έχει διαφορετικό μέγεθος από το συνηθισμένο\nΕίστε σίγουρος ότι θέλετε να συνεχήσετε?", "Προειδοποίηση", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            System.out.println(a);
            
            if (a == 1) return;
        }
        VoucherS voucher = CourierDBM.database.getVoucher(voucherId);
        int id = -1;
        if (voucher == null) {
            CourierDBM.database.saveVoucher(new VoucherS(voucherId));
            id = CourierDBM.database.getVoucher(voucherId).getId();
            System.out.println(id);
        }
        else {
            id = voucher.getId();
        }
        CourierDBM.database.savePackageIn(new PackageInS(id, dist.getdID()-1, MyUtils.dateToString(date)));
        this.voucherID.setText("");
        
        System.out.println(dist.getdID() + " " + dist.getName() + " " + voucherID);
    }//GEN-LAST:event_kataxwrisiButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton kataxwrisiButton;
    private javax.swing.JTextField voucherID;
    // End of variables declaration//GEN-END:variables
}
