/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.riflemansd.courierdb.gui.test;

import java.util.Date;
import org.riflemansd.courierdb.CourierDBM;
import org.riflemansd.courierdb.entrys.dbs.DistributorS;
import org.riflemansd.courierdb.entrys.dbs.PackageOutS;
import org.riflemansd.courierdb.entrys.dbs.VoucherS;
import org.riflemansd.courierdb.gui.searchpreview.GUIDataTestPanelNosearch;
import org.riflemansd.courierdb.utils.MyUtils;

/**
 *
 * @author RiflemanSD
 */
public class Kataxorisi extends javax.swing.JPanel {
    private String voucherBuffer;
    private String codBuffer;
    private NewJFrame gui;
    
    
    /**
     * Creates new form Kataxorisi
     */
    public Kataxorisi() {
        initComponents();
        
        this.gui = null;
        this.voucherBuffer = "";
        this.codBuffer = "";
    }
    public Kataxorisi(NewJFrame gui) {
        initComponents();
        
        this.gui = gui;
        this.voucherBuffer = "";
        this.codBuffer = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        voucherIDTF = new javax.swing.JTextField();
        codTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chargeTF = new javax.swing.JTextField();
        datePicker = new org.riflemansd.courierdb.gui.DatePicker();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        receiptB = new javax.swing.JCheckBox();
        dianomeasPanel1 = new org.riflemansd.courierdb.gui.test.DianomeasPanel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Voucher:");

        voucherIDTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        voucherIDTF.setPreferredSize(new java.awt.Dimension(6, 25));
        voucherIDTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voucherIDTFActionPerformed(evt);
            }
        });
        voucherIDTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                voucherIDTFKeyReleased(evt);
            }
        });

        codTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codTF.setPreferredSize(new java.awt.Dimension(6, 25));
        codTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codTFActionPerformed(evt);
            }
        });
        codTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codTFKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Αντικατ.:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Χρέωση:");

        chargeTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chargeTF.setPreferredSize(new java.awt.Dimension(6, 25));
        chargeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargeTFActionPerformed(evt);
            }
        });
        chargeTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                chargeTFKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Ημερομηνεία:");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Παραλαβή:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator1)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(voucherIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(codTF, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chargeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(datePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(receiptB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dianomeasPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(dianomeasPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(voucherIDTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(codTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chargeTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(receiptB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void voucherIDTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voucherIDTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_voucherIDTFActionPerformed

    private void codTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codTFActionPerformed

    private void chargeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chargeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chargeTFActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        int did = this.dianomeasPanel1.getCurrID();
        String distname = this.dianomeasPanel1.getCurrName();
        
        String voucherID = this.voucherIDTF.getText();
        double cod = MyUtils.stringToDouble(this.codTF.getText());
        double charge = MyUtils.stringToDouble(this.chargeTF.getText());
        String time = MyUtils.dateToString(new Date());
        String rtime = MyUtils.dateToString(this.datePicker.getDate());
        boolean receipt = this.receiptB.isSelected();
        
        insertData(did, distname, voucherID, cod, charge, time, rtime, receipt);
    }//GEN-LAST:event_okButtonActionPerformed

    private void insertData(int did, String distname, String voucherID, double cod, double charge, String time, String rtime, boolean receipt) {
        DistributorS dist = CourierDBM.database.getDistributor(did);
        int distid = dist.getId();
        
        VoucherS voucher = new VoucherS(voucherID, cod, charge, receipt);
        CourierDBM.database.saveVoucher(voucher);
        voucher = CourierDBM.database.getVoucher(voucherID);
        int vid = voucher.getId();
        
        PackageOutS out = new PackageOutS(0, vid, distid, time, rtime);
        CourierDBM.database.savePackageOut(out);
        
        if (gui != null) gui.defineData();
    }
    
    private void voucherIDTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_voucherIDTFKeyReleased
        if (evt.getKeyCode() == 10) {
            String voucher = this.voucherIDTF.getText();
            System.out.println(voucher);
            
            if (voucher.length() == 12) {
                this.voucherBuffer = voucher;
            }
            
            this.codTF.requestFocus();
        }
        else {
            
        }
        
    }//GEN-LAST:event_voucherIDTFKeyReleased

    private void codTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codTFKeyReleased
        if (evt.getKeyCode() == 10) {
            String scod = this.codTF.getText();
            System.out.println(scod);
            
            double cod = toCod(scod);
            if (cod == -2) {
                int did = this.dianomeasPanel1.getCurrID();
                String distname = this.dianomeasPanel1.getCurrName();

                String time = MyUtils.dateToString(new Date());
                String rtime = MyUtils.dateToString(this.datePicker.getDate());
                boolean receipt = this.receiptB.isSelected();
        
                voucherBuffer = scod;
                this.voucherIDTF.setText(scod);
                this.codTF.setText("");
                
                insertData(did, distname, voucherBuffer, 0, 0, time, rtime, receipt);
            }
            else {
                this.chargeTF.requestFocus();
            }
        }
        else {
            try {
                this.codBuffer += "" + evt.getKeyChar();
            }
            catch(Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_codTFKeyReleased

    private void chargeTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chargeTFKeyReleased
        if (evt.getKeyCode() == 10) {
            int did = this.dianomeasPanel1.getCurrID();
            String distname = this.dianomeasPanel1.getCurrName();

            String voucherID = this.voucherIDTF.getText();
            double cod = toCod(this.codTF.getText());
            double charge = toCod(this.chargeTF.getText());
            String time = MyUtils.dateToString(new Date());
            String rtime = MyUtils.dateToString(this.datePicker.getDate());
            boolean receipt = this.receiptB.isSelected();

            System.out.println(cod + " " + charge);
            
            this.voucherIDTF.setText("");
            this.codTF.setText("");
            this.chargeTF.setText("");
            this.voucherIDTF.requestFocus();
            
            insertData(did, distname, voucherID, cod, charge, time, rtime, receipt);
        }
    }//GEN-LAST:event_chargeTFKeyReleased

    private double toCod(String cod) {
        cod = cod.replace(",", ".");
        
        if (cod.length() == 0) return 0;
        
        if (cod.contains(".") || cod.length() <= 4) {
            try {
                return Double.parseDouble(cod);
            }
            catch (Exception e) {
                return -1;
            }
        }
        else {
            if (cod.length() == 12) return -2;
            
            return -1;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField chargeTF;
    private javax.swing.JTextField codTF;
    private org.riflemansd.courierdb.gui.DatePicker datePicker;
    private org.riflemansd.courierdb.gui.test.DianomeasPanel dianomeasPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton okButton;
    private javax.swing.JCheckBox receiptB;
    private javax.swing.JTextField voucherIDTF;
    // End of variables declaration//GEN-END:variables
}
