/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.riflemansd.courierdb.gui.test;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import org.riflemansd.courierdb.CourierDBM;
import org.riflemansd.courierdb.entrys.dbs.DistributorS;
import org.riflemansd.courierdb.entrys.dbs.VoucherS;
import org.riflemansd.courierdb.gui.excel.MyExcelDocument;
import org.riflemansd.courierdb.gui.searchpreview.GUIDataTestPanel;
import org.riflemansd.courierdb.gui.searchpreview.GUIDataTestPanelNosearch;
import org.riflemansd.courierdb.utils.MyUtils;
import org.riflemansd.courierdb.utils.OpenProjectFiles;

/**
 *
 * @author RiflemanSD
 */
public class NewJFrame extends javax.swing.JFrame {
    private String date;
    GUIDataTestPanelNosearch gui;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        gui = new GUIDataTestPanelNosearch("VoucherID,Αντικαταβολή,Χρέωση,Διανομέας,Παραλαβή,Ημερομηνεία", "s",1.0,1.0,"s",true,new Date());
        this.date = "24-05-2016";
        
        gui.setTitleName("Ημερομηνεία: " + date);
        defineData();
        
        this.jPanel1.add(gui, BorderLayout.CENTER);
    }
    
    public void defineData() {
        gui.clear();
        
        String[] data = CourierDBM.database.getVouchersByRTime(this.date);
        
        for (String d : data) {
            String[] line = d.split(",");
            
            int voucherid = MyUtils.stringToInt(line[0]); //voucherid
            VoucherS voucher = CourierDBM.database.getVoucher(voucherid);
            
            int distId = MyUtils.stringToInt(line[1]); //distid
            DistributorS dist = CourierDBM.database.getDistributorByID(distId);
            
            String vdate = line[2];
            
            gui.addRow(voucher.getName(), voucher.getCodcash(), voucher.getChargecash(), dist.getName(), voucher.isReceipt(), vdate);
        }
        
        gui.sort();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kataxorisi1 = new org.riflemansd.courierdb.gui.test.Kataxorisi();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kataxorisi1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jMenu1.setText("File");

        jMenuItem1.setText("Export Excel...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kataxorisi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kataxorisi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String fileName = "database";

        fileName += ".xlsx";
        System.out.println(fileName);

        int numberOfColumns = gui.table.getColumnCount();
        int numberOfRows = gui.table.getRowCount();

        MyExcelDocument doc = new MyExcelDocument(fileName);

        for (int i = 0; i < numberOfColumns; i++) {
            String header = (String) gui.table.getColumn(i).getHeaderValue();

            doc.setHeader(0, 0, i, header);
        }

        for (int i = 1; i < numberOfRows; i++) {
            Object[] datas = gui.table.getRowAt(i);

            int j = 0;
            //datas[0] = Integer.parseInt((String) datas[0]);
            for (Object o : datas) {
                if (o instanceof Integer) {
                    doc.setDouble(0, i, j, (int) o);
                } else if (o instanceof Number) {
                    doc.setDouble(0, i, j, (double) o);
                } else if (o instanceof Date) {
                    doc.setDate(0, i, j, (Date) o);
                } else if (o instanceof Boolean) {
                    doc.setString(0, i, j, MyUtils.booleanToString((boolean)o));
                } else {
                    doc.setString(0, i, j, (String) o);
                }
                j++;
            }
        }
        for (int i = 0; i < numberOfRows; i++) {
            doc.autoFillColumhWidth(0, i);
        }
        doc.save();

        OpenProjectFiles.openFile(fileName);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private org.riflemansd.courierdb.gui.test.Kataxorisi kataxorisi1;
    // End of variables declaration//GEN-END:variables

}
