/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.riflemansd.courierdb.gui.test;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import org.riflemansd.courierdb.CourierDBM;
import org.riflemansd.courierdb.entrys.dbs.CourierS;
import org.riflemansd.courierdb.entrys.dbs.VoucherS;
import org.riflemansd.courierdb.gui.excel.MyExcelDocument;
import org.riflemansd.courierdb.gui.searchpreview.GUIDataTestPanel;
import org.riflemansd.courierdb.gui.searchpreview.GUIDataTestPanelNosearch;
import org.riflemansd.courierdb.utils.MyUtils;
import org.riflemansd.courierdb.utils.OpenProjectFiles;

/**
 *
 * @author RiflemanSD
 */
public class Tameio extends javax.swing.JFrame {
    private String date;
    GUIDataTestPanelNosearch gui;
    GUIDataTestPanelNosearch gui2;
    /**
     * Creates new form NewJFrame
     */
    public Tameio() {
        initComponents();
        
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        gui2 = new GUIDataTestPanelNosearch("Διανομέας,Σύνολο,Παραδόσεις,Παραλαβές", "s", 1.0, 1, 1);
        this.date = "24-05-2016";
        
        gui2.setTitleName("Χρήματα Διανομέων");
        
        this.jPanel1.add(gui2, BorderLayout.CENTER);
        
        this.jPanel2.setLayout(new BorderLayout());
        
        gui = new GUIDataTestPanelNosearch("VoucherID,Αντικαταβολή,Χρέωση,Διανομέας,Παραλαβή,Ημερομηνεία", "s",1.0,1.0,"s",true,new Date());
        gui.setTitleName("Ημερομηνεία: " + date);
        
        this.jPanel2.add(gui, BorderLayout.CENTER);
        
        defineData();
    }
    
    public void defineData() {
        gui.clear();
        HashMap<String, Double> cods = new HashMap<>();
        HashMap<String, Integer> paradoseis = new HashMap<>();
        HashMap<String, Integer> paralabes = new HashMap<>();
        
        String[] data = CourierDBM.database.getVouchersByTime(this.date);
        
        for (String d : data) {
            String[] line = d.split(",");
            
            int voucherid = MyUtils.stringToInt(line[0]); //voucherid
            VoucherS voucher = CourierDBM.database.getVoucher(voucherid);
            
            int distId = MyUtils.stringToInt(line[1]); //distid
            CourierS dist = CourierDBM.database.getCourierByID(distId);
            
            String n = dist.getName();
            Double c = voucher.getCodcash() + voucher.getChargecash();
            if (cods.containsKey(n)) cods.put(n, cods.get(n) + c);
            else cods.put(n, c);
            
            if (voucher.isReceipt()) {
                if (paralabes.containsKey(n)) paralabes.put(n, paralabes.get(n) + 1);
                else paralabes.put(n, 1);
            }
            else {
                if (paradoseis.containsKey(n)) paradoseis.put(n, paradoseis.get(n) + 1);
                else paradoseis.put(n, 1);
            }
            
            String vdate = line[2];
            
            gui.addRow(voucher.getName(), voucher.getCodcash(), voucher.getChargecash(), dist.getName(), voucher.isReceipt(), vdate);
        }
        gui.sort();
        
        
        
        gui2.clear();
        
        for (String k : cods.keySet()) {
            gui2.addRow(k, cods.get(k), paradoseis.get(k), paralabes.get(k));
        }
        
        gui2.sort();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kataxorisi1 = new org.riflemansd.courierdb.gui.test.Kataxorisi();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kataxorisi1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Export Excel...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kataxorisi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kataxorisi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 294, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String fileName = "database";

        fileName += ".xlsx";
        System.out.println(fileName);

        HashMap<String, Double> cods = new HashMap<>();
        HashMap<String, Double> charges = new HashMap<>();
        ArrayList<String> paradoseis = new ArrayList<>();
        ArrayList<String> paralabes = new ArrayList<>();
        double sum = 0;
        int par = 0;
        int pal = 0;
        
        int numberOfRows = gui.table.getRowCount();

        MyExcelDocument doc = new MyExcelDocument(fileName, true);
        

        for (int i = 1; i < numberOfRows; i++) {
            Object[] datas = gui.table.getRowAt(i);

            String voucherid = (String) datas[0];
            double cod = (double) datas[1];
            double charge = (double) datas[2];
            boolean rec = (boolean) datas[4];
            
            if (cod == 0 && charge == 0) {
                if (rec) {paralabes.add(voucherid);}
                else {paradoseis.add(voucherid);}
            }
            if (cod != 0) {
                cods.put(voucherid, cod);
                sum += cod;
            }
            if (charge != 0) {
                charges.put(voucherid, charge);
                sum += charge;
            }
            if (rec) pal++;
            else par++;
            
            System.out.println(voucherid + " " + cod + " " + charge + " " + rec);
        }
        doc.setHeader(0, 0, 0, "Παραδόσεις " + date, 20, true);
        doc.mergeCells(0, 0, 0, 0, 4);
        
        int i = 1, j = 0;
        if (!cods.isEmpty()) {
            doc.setHeader(0, i, 0, "Αντικαταβολές", 14, true);
            doc.mergeCells(0, i, i, j, j+1);
            i++;
        }
        for (String k : cods.keySet()) {
            
            if (i > 40) {
                i = 1;
                j = 2;
            }
            
            doc.setString(0, i, j, k);
            doc.setDouble(0, i, j+1, cods.get(k), "0.00 €");
            doc.addBorders(0, i, j);
            doc.addBorders(0, i, j+1);
            i++;
        }
        if (!charges.isEmpty()) {
            doc.setHeader(0, i, 0, "Χρεώσεις", 14, true);
            doc.mergeCells(0, i, i, j, j+1);
            i++;
        }
        for (String k : charges.keySet()) {
            
            if (i > 40) {
                i = 1;
                j = 2;
            }
            
            doc.setString(0, i, j, k);
            doc.setDouble(0, i, j+1, charges.get(k), "0.00 €");
            i++;
        }
        if (!paradoseis.isEmpty()) {
            doc.setHeader(0, i, 0, "Παραδόσεις", 14, true);
            doc.mergeCells(0, i, i, j, j+1);
            i++;
        }
        for (String k : paradoseis) {
            
            if (i > 40) {
                i = 1;
                j = 2;
            }
            
            doc.setString(0, i, j, k);
            i++;
        }
        if (!paralabes.isEmpty()) {
            doc.setHeader(0, i, 0, "Παραλαβές", 14, true);
            doc.mergeCells(0, i, i, j, j+1);
            i++;
        }
        
        for (String k : paralabes) {
            
            if (i > 40) {
                i = 1;
                j = 2;
            }
            
            doc.setString(0, i, j, k);
            i++;
        }
        
        doc.setRowHeight(0, 43, 20);
        doc.setHeader(0, 45, 0, "Σύνολο: ", 16, true);
        doc.setDouble(0, 45, 1, sum, "0.00 €", 16, true);
        doc.setHeader(0, 45, 2, "Παραδόσεις: " + par, 12, false);
        doc.setHeader(0, 45, 3, "Παραλαβές: " + pal, 12, false);
        
        for (i = 0; i < 4; i++) {
            doc.autoFillColumhWidth(0, i);
        }
        doc.save();
        OpenProjectFiles.openFile(fileName);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tameio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tameio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tameio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tameio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tameio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.riflemansd.courierdb.gui.test.Kataxorisi kataxorisi1;
    // End of variables declaration//GEN-END:variables

}
