/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.riflemansd.courierdb.gui;

import java.awt.BorderLayout;
import java.util.Date;
import javax.swing.JLabel;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author user01
 */
public class CustomerFormComboBox extends javax.swing.JPanel {
    private TimePicker timePicker;
    private JXDatePicker datePicker;
    /**
     * Creates new form NewJPanel
     */
    public CustomerFormComboBox() {
        initComponents();
        datePicker = new JXDatePicker(new Date());
        this.datePanel.add(datePicker, BorderLayout.CENTER);
        this.datePanel.add(new JLabel("Ημερομηνία:"), BorderLayout.PAGE_START);
        //this.datePanel.add(new JXTextField("Πεύκα"), BorderLayout.CENTER);
        //this.datePanel.add(new JXLabel("kotes"), BorderLayout.CENTER);
        //this.datePanel.add(new JXButton("kotes"), BorderLayout.CENTER);
        //this.datePanel.add(new JXFormattedTextField("Lakis"), BorderLayout.CENTER);
        timePicker = new TimePicker("HH:mm");
        this.timePanel.setLayout(new BorderLayout());
        this.timePanel.add(timePicker, BorderLayout.CENTER);
        this.timePanel.add(new JLabel("Ώρα:"), BorderLayout.PAGE_START);
        
        this.nameTF.setPrompt("Σωτήρης Δούδης");
        this.addressTF.setPrompt("Εμμανουήλ Παππά 7");
        this.cityTF.setPrompt("Ασβεστοχώρι");
        this.courierTF.setPrompt("ΔΟΥΔΗ");
        this.afmTF.setPrompt("");
        this.phoneTF.setPrompt("2310358246");
        this.postcodeTF.setPrompt("57010");
        this.signTF.setPrompt("Σωτήρης Δούδης");
        
        this.nameTF.setWords("Σωτήρης Δούδης", "Βαγγέλης Δούδης", "Δημήτρης Δούδης");
        this.addressTF.setWords("Εμμανουήλ Παππα 7", "Εμμανουήλ Παππά 31", "Παύλου Μελά 32");
        this.cityTF.setWords("Πεύκα", "Ασβεστοχώρι", "Φίλυρο", "Χορτιάτης");
        this.courierTF.setWords("ΔΟΥΔΗ");
        this.afmTF.setWords("");
        this.phoneTF.setWords("2310358246", "2310358214", "6943915388");
        this.postcodeTF.setWords("57010");
        this.signTF.setWords("Σωτήρης Δούδης", "Βαγγέλης Δούδης", "Δημήτρης Δούδης");
    }

    public String[] getData() {
        String[] data = new String[10];
        
        data[0] = this.nameTF.getValue();
        data[1] = this.addressTF.getValue();
        data[2] = this.cityTF.getValue();
        data[3] = this.postcodeTF.getValue();
        data[4] = this.phoneTF.getValue();
        data[5] = this.afmTF.getValue();
        data[6] = this.signTF.getValue();
        data[7] = this.courierTF.getValue();
        data[8] = this.datePicker.getDate().toString();
        data[9] = this.timePicker.getTime();
        
        return data;
    }
    public void setData(String... data) {
        this.nameTF.setValue(data[0]);
        this.addressTF.setValue(data[1]);
        this.cityTF.setValue(data[2]);
        this.postcodeTF.setValue(data[3]);
        this.phoneTF.setValue(data[4]);
        this.afmTF.setValue(data[5]);
        this.signTF.setValue(data[6]);
        this.courierTF.setValue(data[7]);
        this.datePicker.setDate(new Date(data[8]));
        this.timePicker.setTime(new Date(data[9]));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        datePanel = new javax.swing.JPanel();
        timePanel = new javax.swing.JPanel();
        nameTF = new org.riflemansd.courierdb.gui.JComboBoxAutoCompletePanel();
        addressTF = new org.riflemansd.courierdb.gui.JComboBoxAutoCompletePanel();
        cityTF = new org.riflemansd.courierdb.gui.JComboBoxAutoCompletePanel();
        postcodeTF = new org.riflemansd.courierdb.gui.JComboBoxAutoCompletePanel();
        phoneTF = new org.riflemansd.courierdb.gui.JComboBoxAutoCompletePanel();
        afmTF = new org.riflemansd.courierdb.gui.JComboBoxAutoCompletePanel();
        signTF = new org.riflemansd.courierdb.gui.JComboBoxAutoCompletePanel();
        courierTF = new org.riflemansd.courierdb.gui.JComboBoxAutoCompletePanel();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Όνομα");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Διευθ.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Πόλη");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Τ.Κωδ.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Τηλ.");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Α.Φ.Μ.");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Υπέγραψε");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Διανομέας");

        datePanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout timePanelLayout = new javax.swing.GroupLayout(timePanel);
        timePanel.setLayout(timePanelLayout);
        timePanelLayout.setHorizontalGroup(
            timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );
        timePanelLayout.setVerticalGroup(
            timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );

        nameTF.setPreferredSize(new java.awt.Dimension(127, 25));

        addressTF.setPreferredSize(new java.awt.Dimension(127, 25));

        cityTF.setPreferredSize(new java.awt.Dimension(127, 25));

        postcodeTF.setPreferredSize(new java.awt.Dimension(127, 25));

        phoneTF.setPreferredSize(new java.awt.Dimension(127, 25));

        afmTF.setPreferredSize(new java.awt.Dimension(127, 25));

        signTF.setPreferredSize(new java.awt.Dimension(127, 25));

        courierTF.setPreferredSize(new java.awt.Dimension(127, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(afmTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phoneTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(postcodeTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cityTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addressTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(datePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(courierTF, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(signTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(9, 9, 9)
                                                .addComponent(jLabel2))
                                            .addComponent(addressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel3))
                                    .addComponent(cityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addComponent(jLabel4))
                            .addComponent(postcodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5))
                    .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(afmTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(signTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courierTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(timePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(datePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.riflemansd.courierdb.gui.JComboBoxAutoCompletePanel addressTF;
    private org.riflemansd.courierdb.gui.JComboBoxAutoCompletePanel afmTF;
    private org.riflemansd.courierdb.gui.JComboBoxAutoCompletePanel cityTF;
    private org.riflemansd.courierdb.gui.JComboBoxAutoCompletePanel courierTF;
    private javax.swing.JPanel datePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private org.riflemansd.courierdb.gui.JComboBoxAutoCompletePanel nameTF;
    private org.riflemansd.courierdb.gui.JComboBoxAutoCompletePanel phoneTF;
    private org.riflemansd.courierdb.gui.JComboBoxAutoCompletePanel postcodeTF;
    private org.riflemansd.courierdb.gui.JComboBoxAutoCompletePanel signTF;
    private javax.swing.JPanel timePanel;
    // End of variables declaration//GEN-END:variables
}
